"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";

type Resource={id:string;name:string;status:string;product_type:string;copyright_status:string;is_sponsored:boolean};
export default function AdminResourcesPage(){
  const[items,setItems]=useState<Resource[]>([]);const[error,setError]=useState("");const[message,setMessage]=useState("");
  const[form,setForm]=useState({name:"",product_type:"physical_book",description:"",provider_name:"",price:"",is_free:false,external_url:"",related_attributes:"mathematical_foundation",related_task_tags:"",applicable_goal_types:"",copyright_status:"verified",source_type:"admin_entry",is_sponsored:false,sponsorship_label:"",status:"draft"});
  async function load(){try{setItems(await apiRequest<Resource[]>("/admin/resources"))}catch(reason){setError(reason instanceof Error?reason.message:"加载失败")}}
  useEffect(()=>{load()},[]);
  async function create(){try{await apiRequest("/admin/resources",{method:"POST",body:JSON.stringify({...form,price:form.price?Number(form.price):null,applicable_stages:[],related_attributes:form.related_attributes.split(",").filter(Boolean),related_task_tags:form.related_task_tags.split(",").map(x=>x.trim()).filter(Boolean),applicable_goal_types:form.applicable_goal_types.split(",").map(x=>x.trim()).filter(Boolean),free_alternative_ids:[]})});setMessage("资源已创建为草稿");setForm({...form,name:"",description:""});await load()}catch(reason){setError(reason instanceof Error?reason.message:"创建失败")}}
  async function status(id:string,value:string){await apiRequest(`/admin/resources/${id}`,{method:"PATCH",body:JSON.stringify({status:value})});await load()}
  return <main className="mx-auto max-w-6xl p-6"><h1 className="text-2xl font-bold">管理员资源管理</h1><p className="text-sm text-gray-600">权限由后端角色校验。资源创建后需明确上架才会展示。</p>{error&&<p className="mt-3 text-red-600">{error}</p>}{message&&<p className="mt-3 text-green-700">{message}</p>}
    <section className="mt-5 grid gap-2 md:grid-cols-2"><input className="border px-3 py-2" placeholder="资源名称" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select aria-label="商品类型" className="border px-3 py-2" value={form.product_type} onChange={e=>setForm({...form,product_type:e.target.value})}><option value="free_resource">免费资源</option><option value="digital_material">数字资料</option><option value="physical_book">实体书</option><option value="recorded_course">录播课程</option><option value="assessment">测评</option><option value="other">其他</option></select><textarea className="border px-3 py-2" placeholder="资源描述" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className="border px-3 py-2" placeholder="提供方" value={form.provider_name} onChange={e=>setForm({...form,provider_name:e.target.value})}/><input className="border px-3 py-2" placeholder="价格" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input className="border px-3 py-2" placeholder="原始外部链接" value={form.external_url} onChange={e=>setForm({...form,external_url:e.target.value})}/><input className="border px-3 py-2" placeholder="任务标签，逗号分隔" value={form.related_task_tags} onChange={e=>setForm({...form,related_task_tags:e.target.value})}/><input className="border px-3 py-2" placeholder="目标类型，逗号分隔" value={form.applicable_goal_types} onChange={e=>setForm({...form,applicable_goal_types:e.target.value})}/><select aria-label="关联能力" className="border px-3 py-2" value={form.related_attributes} onChange={e=>setForm({...form,related_attributes:e.target.value})}><option value="mathematical_foundation">数理基础</option><option value="english">英语</option><option value="professional_knowledge">专业知识</option><option value="data_analysis">数据分析</option><option value="programming_tools">编程工具</option></select><select aria-label="版权状态" className="border px-3 py-2" value={form.copyright_status} onChange={e=>setForm({...form,copyright_status:e.target.value})}><option value="verified">已核验</option><option value="provider_owned">提供方所有</option><option value="licensed">已授权</option><option value="public">公开资源</option><option value="pending">待确认</option><option value="unknown">未知</option></select><label><input type="checkbox" checked={form.is_free} onChange={e=>setForm({...form,is_free:e.target.checked,price:e.target.checked?"0":form.price})}/> 免费</label><label><input type="checkbox" checked={form.is_sponsored} onChange={e=>setForm({...form,is_sponsored:e.target.checked})}/> 商业推广</label><button className="bg-slate-900 px-4 py-2 text-white md:col-span-2" onClick={create}>创建资源草稿</button></section>
    <section className="mt-6"><h2 className="font-semibold">资源列表</h2>{items.length===0?<p className="text-gray-600">资源库为空。</p>:items.map(item=><article className="mt-3 flex items-center gap-3 border p-4" key={item.id}><div><b>{item.name}</b><p className="text-sm">{item.product_type} / {item.status} / {item.copyright_status}{item.is_sponsored?" / 推广":""}</p></div><button className="ml-auto border px-3 py-2" onClick={()=>status(item.id,"active")}>上架</button><button className="border px-3 py-2" onClick={()=>status(item.id,"inactive")}>下架</button><button className="border px-3 py-2" onClick={()=>status(item.id,"outdated")}>标记过期</button></article>)}</section>
  </main>;
}
