"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";
import type { Goal } from "@/types";

type Item = { id: string; title: string; task_type: string; estimated_minutes: number; deadline: string; completion_standard: string; evidence_requirements: string; generation_reason: string };
type Plan = { id: string; status: string; items: Item[] };
type AIAnalysis = { id: string; result_json: { items: Array<Pick<Item, "id" | "title" | "completion_standard" | "evidence_requirements" | "generation_reason">> } };

export default function WeeklyPlanPage() {
  const [goals, setGoals] = useState<Goal[]>([]); const [goalId, setGoalId] = useState(""); const [plan, setPlan] = useState<Plan | null>(null);
  const [analysis, setAnalysis] = useState<AIAnalysis | null>(null); const [loading, setLoading] = useState(true); const [aiLoading, setAiLoading] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { apiRequest<Goal[]>("/goals").then((data) => { setGoals(data); if (data[0]) setGoalId(data[0].id); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  async function generate() { try { setPlan(await apiRequest<Plan>(`/weekly-plans${goalId ? `?goal_id=${goalId}` : ""}`, { method: "POST" })); setAnalysis(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "生成失败"); } }
  async function optimize() { if (!plan) return; setAiLoading(true); try { const response = await apiRequest<{ analysis: AIAnalysis | null }>(`/weekly-plans/${plan.id}/ai-optimize`, { method: "POST" }); setAnalysis(response.analysis); setMessage(response.analysis ? "AI 优化草稿待确认，时长、类型和截止日期保持规则结果。" : "AI 当前不可用，规则计划仍可直接确认。"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "AI 当前不可用"); } finally { setAiLoading(false); } }
  async function applyOptimization() { if (!analysis || !plan) return; await apiRequest(`/ai/analyses/${analysis.id}/confirm-plan`, { method: "POST" }); const replacements = new Map(analysis.result_json.items.map((item) => [item.id, item])); setPlan({ ...plan, items: plan.items.map((item) => ({ ...item, ...replacements.get(item.id) })) }); setAnalysis(null); setMessage("AI 文案草稿已应用，计划仍需你的最终确认。"); }
  async function confirm() { if (!plan) return; setPlan(await apiRequest<Plan>(`/weekly-plans/${plan.id}/confirm`, { method: "POST", body: JSON.stringify({ accepted_item_ids: plan.items.map((item) => item.id) }) })); }
  return <main className="mx-auto max-w-5xl p-6"><h1 className="text-2xl font-bold">七日计划预览与确认</h1>{loading ? <p>加载中...</p> : <><select aria-label="计划目标" className="mt-4 border px-3 py-2" value={goalId} onChange={(event) => setGoalId(event.target.value)}><option value="">未指定目标</option>{goals.map((goal) => <option key={goal.id} value={goal.id}>{goal.target_major || goal.target_school || "未命名目标"}</option>)}</select><button className="ml-2 border bg-slate-900 px-4 py-2 text-white" onClick={generate}>生成七日计划</button></>}{error && <p className="text-red-600">{error}</p>}{message && <p className="mt-2 text-sm text-gray-600">{message}</p>}{plan && <section className="mt-5"><p>计划状态：{plan.status}</p>{plan.items.length === 0 ? <p className="text-gray-600">没有可生成且不重复的任务。</p> : plan.items.map((item) => { const preview = analysis?.result_json.items.find((value) => value.id === item.id); const visible = preview ? { ...item, ...preview } : item; return <article className="mt-3 border p-4" key={item.id}><b>{visible.title}</b><p>{item.task_type} / {item.estimated_minutes} 分钟 / 截止 {new Date(item.deadline).toLocaleDateString()}</p><p>完成标准：{visible.completion_standard}</p><p>证据要求：{visible.evidence_requirements}</p><p className="text-sm text-gray-600">原因：{visible.generation_reason}</p></article>; })}{plan.status === "draft" && plan.items.length > 0 && <div className="mt-4 flex gap-2"><button className="border px-4 py-2" onClick={optimize} disabled={aiLoading}>{aiLoading ? "AI 优化中..." : "AI 优化任务"}</button>{analysis && <button className="border px-4 py-2" onClick={applyOptimization}>应用 AI 优化草稿</button>}<button className="border bg-slate-900 px-4 py-2 text-white" onClick={confirm}>确认计划并写入任务中心</button></div>}{plan.status === "confirmed" && <p className="mt-4 text-green-700">计划已确认，任务已写入任务中心。</p>}</section>}</main>;
}
