"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";

type Recommendation = { resource_id: string; name: string; product_type: string; price: number | null; currency: string; is_free: boolean; relevance_score: number; recommendation_reason: string; related_attribute: string | null; related_task: string | null; budget_fit: boolean; already_owned_similar: boolean; free_alternative_ids: string[]; sponsored: boolean; sponsorship_label: string | null; is_required: boolean; favorited: boolean; warnings: string[] };

export default function ResourcesPage() {
  const [items, setItems] = useState<Recommendation[]>([]); const [search, setSearch] = useState(""); const [type, setType] = useState(""); const [attribute, setAttribute] = useState(""); const [freeOnly, setFreeOnly] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { setItems(await apiRequest<Recommendation[]>("/resource-recommendations")); } catch (reason) { setError(reason instanceof Error ? reason.message : "加载失败"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  async function favorite(id: string) { await apiRequest(`/resources/${id}/favorite`, { method: "PUT" }); await load(); }
  async function own(item: Recommendation) { await apiRequest("/owned-resources", { method: "POST", body: JSON.stringify({ resource_product_id: item.resource_id, resource_type: item.product_type }) }); await load(); }
  async function dismiss(id: string) { await apiRequest(`/resources/${id}/interactions`, { method: "POST", body: JSON.stringify({ interaction_type: "dismissed" }) }); await load(); }
  const shown = items.filter((item) => (!search || item.name.toLowerCase().includes(search.toLowerCase())) && (!type || item.product_type === type) && (!attribute || item.related_attribute === attribute) && (!freeOnly || item.is_free));
  return <main className="mx-auto max-w-6xl p-6"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold">学习资源中心</h1><Link className="ml-auto underline" href="/resources/favorites">我的收藏</Link><Link className="underline" href="/resources/owned">我的资源</Link></div><p className="mt-2 text-sm text-gray-600">推荐来自当前任务、已确认目标要求、真实差距、档案预算和已有资源。购买不是完成主线任务的必要条件。</p>
    <section className="mt-5 flex flex-wrap gap-2"><input aria-label="搜索资源" className="border px-3 py-2" placeholder="搜索" value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="资源类型" className="border px-3 py-2" value={type} onChange={(event) => setType(event.target.value)}><option value="">全部类型</option><option value="free_resource">免费资源</option><option value="digital_material">数字资料</option><option value="physical_book">实体书</option><option value="recorded_course">录播课</option><option value="assessment">测评</option><option value="other">其他</option></select><select aria-label="关联能力筛选" className="border px-3 py-2" value={attribute} onChange={(event) => setAttribute(event.target.value)}><option value="">全部能力</option><option value="mathematical_foundation">数理基础</option><option value="english">英语</option><option value="professional_knowledge">专业知识</option><option value="data_analysis">数据分析</option><option value="programming_tools">编程工具</option></select><label className="flex items-center gap-2"><input type="checkbox" checked={freeOnly} onChange={(event) => setFreeOnly(event.target.checked)} />仅免费</label></section>
    {loading ? <p className="mt-5">加载中...</p> : error ? <p className="mt-5 text-red-600">{error}</p> : shown.length === 0 ? <p className="mt-5 text-gray-600">当前没有符合条件的已上架资源。</p> : <section className="mt-5 grid gap-4 md:grid-cols-2">{shown.map((item) => <article key={item.resource_id} className="border p-4"><div className="flex justify-between"><h2 className="font-semibold">{item.name}</h2>{item.sponsored ? <span className="text-xs text-amber-700">{item.sponsorship_label || "推广"}</span> : <span className="text-xs text-gray-500">自然推荐</span>}</div><p>{item.is_free ? "免费" : `${item.price ?? "价格未提供"} ${item.currency}`}</p><p className="mt-2 text-sm">推荐原因：{item.recommendation_reason}</p><p className="text-sm">关联能力：{item.related_attribute || "无直接关联"}</p><p className="text-sm">关联任务：{item.related_task || "无直接关联"}</p><p className="text-sm">是否必要：{item.is_required ? "必要" : "非必要"} / 免费替代：{item.free_alternative_ids.length ? "有" : "无"}</p>{item.already_owned_similar && <p className="text-sm text-amber-700">已拥有同类资源</p>}{item.warnings.map((warning) => <p key={warning} className="text-sm text-amber-700">{warning}</p>)}<div className="mt-3 flex flex-wrap gap-2"><Link className="border px-3 py-2" href={`/resources/${item.resource_id}`}>查看详情</Link><button className="border px-3 py-2" onClick={() => favorite(item.resource_id)}>收藏</button><button className="border px-3 py-2" onClick={() => own(item)}>标记已有</button><button className="border px-3 py-2" onClick={() => dismiss(item.resource_id)}>不感兴趣</button></div></article>)}</section>}
  </main>;
}
