"use client";
import { useCallback,useEffect,useState } from 'react';import { apiRequest } from '@/lib/api';import type { Goal } from '@/types';
type Requirement={id:string;title:string;category:string;verification_status:string;target_min:number|null;unit:string|null};
type Gap={requirement_id:string;title:string;gap_level:string;current_status:string;confidence:number;missing_evidence:string[];next_step:string};
export default function GoalAnalysisPage(){const [goals,setGoals]=useState<Goal[]>([]);const [goalId,setGoalId]=useState('');const [requirements,setRequirements]=useState<Requirement[]>([]);const [gaps,setGaps]=useState<Gap[]>([]);const [form,setForm]=useState({category:'mathematical_foundation',title:'',metric_type:'ratio',target_min:'',unit:'',source_type:'user_input',verification_status:'confirmed'});const [loading,setLoading]=useState(true);const [error,setError]=useState('');
useEffect(()=>{apiRequest<Goal[]>('/goals').then(data=>{setGoals(data);if(data[0])setGoalId(data[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
const load=useCallback(async(id:string)=>{if(!id)return;try{setRequirements(await apiRequest<Requirement[]>(`/goals/${id}/requirements`));setGaps(await apiRequest<Gap[]>(`/goals/${id}/gaps`));}catch(e){setError(e instanceof Error?e.message:'加载失败')}},[]);useEffect(()=>{if(goalId)load(goalId)},[goalId,load]);
async function add(){if(!goalId)return;await apiRequest(`/goals/${goalId}/requirements`,{method:'POST',body:JSON.stringify({...form,target_min:form.target_min?Number(form.target_min):null})});await load(goalId)}
return <main className="mx-auto max-w-6xl p-6"><h1 className="text-2xl font-bold">目标要求与差距分析</h1>{loading?<p>加载中...</p>:goals.length===0?<p className="mt-3 text-gray-600">请先在目标页面创建目标。</p>:<><select aria-label="选择目标" className="mt-4 border px-3 py-2" value={goalId} onChange={e=>setGoalId(e.target.value)}>{goals.map(g=><option key={g.id} value={g.id}>{g.target_major||g.target_school||'未命名目标'}</option>)}</select>{error&&<p className="text-red-600">{error}</p>}<section className="mt-5 grid gap-2 md:grid-cols-4"><select aria-label="要求类别" className="border px-2" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="mathematical_foundation">数学要求</option><option value="english">英语要求</option><option value="professional_knowledge">专业课要求</option><option value="programming_tools">编程要求</option><option value="academic_research">科研或复试要求</option><option value="other">其他要求</option></select><input className="border px-3 py-2" placeholder="要求标题" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="border px-3 py-2" placeholder="目标最低值（可选）" type="number" value={form.target_min} onChange={e=>setForm({...form,target_min:e.target.value})}/><input className="border px-3 py-2" placeholder="单位（可选）" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><button className="border bg-slate-900 px-4 py-2 text-white md:col-span-4" onClick={add}>添加已确认要求</button></section><section className="mt-6"><h2 className="font-semibold">要求与差距</h2>{requirements.length===0?<p className="text-gray-600">尚无目标要求。</p>:requirements.map(req=>{const gap=gaps.find(x=>x.requirement_id===req.id);return <article className="mt-3 border p-4" key={req.id}><b>{req.title}</b><p className="text-sm">{req.category} / {req.verification_status}</p>{gap&&<><p>差距：{gap.gap_level} / 当前：{gap.current_status}</p><p>可信度：{Math.round(gap.confidence*100)}%</p><p className="text-sm text-gray-600">{gap.missing_evidence.join('；')||gap.next_step}</p></>}</article>})}</section></>}</main>}
